GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bobby",
    "number": "313131-686868"
}

###

DELETE http://radiant-plateau-76557.herokuapp.com/api/persons/4269

###

POST http://radiant-plateau-76557.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "marblesharblelarble", 
    "number": "721212121"
}