POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "LiveOverflow",
    "author": "Fabian Faessler",
    "url": "https://liveoverflow.com/topic/blog/",
    "likes": 1
}

###

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "CTFTime",
    "author": "",
    "url": "https://ctftime.org",
    "likes": 5
}